# config_cpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: us-west1-b-docker.pkg.dev/mlops-project-484509/mlops-project-artifacts/mlops-train-image:latest
